version: '3.1'

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres-api-catalog
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_catalog_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
